// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/task-assignment/": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist"
                ],
                "summary": "Get All Tasklist",
                "responses": {}
            }
        },
        "/api/v1/task-assignment/approval": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist"
                ],
                "summary": "Approve Tasklist",
                "parameters": [
                    {
                        "description": "Approval Request",
                        "name": "approvalRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/riskmanagement_models_taskassignment.ApprovalRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/task-assignment/checkTableExist": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist"
                ],
                "summary": "Check If Table Exist",
                "parameters": [
                    {
                        "description": "Task Filter",
                        "name": "taskFilter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CheckTableRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/task-assignment/deleteLampiran": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist"
                ],
                "summary": "Delete Lampiran",
                "parameters": [
                    {
                        "description": "Task Filter",
                        "name": "taskFilter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DataTematikRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/task-assignment/deleteTasklist": {
            "delete": {
                "tags": [
                    "Tasklist"
                ],
                "summary": "Delete Tasklist",
                "parameters": [
                    {
                        "description": "Delete Payload",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DeleteTasklistDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/task-assignment/generateNoTask": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist"
                ],
                "summary": "Generate No Task",
                "parameters": [
                    {
                        "description": "Task Filter",
                        "name": "taskFilter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.NoTaskRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/task-assignment/getDetailTematik": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist"
                ],
                "summary": "Get Detail Tematik",
                "parameters": [
                    {
                        "description": "Task Filter",
                        "name": "taskFilter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DataTematikRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/task-assignment/getRejectionNotes": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist"
                ],
                "summary": "Get Rejection Notes",
                "parameters": [
                    {
                        "description": "Task Filter",
                        "name": "taskFilter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TaskDetailRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/task-assignment/getTaskApprovalList": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist"
                ],
                "summary": "Get Data Task Approval List",
                "parameters": [
                    {
                        "description": "Task Filter",
                        "name": "taskFilter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TaskApprovalRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/task-assignment/getTaskData": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist"
                ],
                "summary": "Get Data Task",
                "parameters": [
                    {
                        "description": "Task Filter",
                        "name": "taskFilter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TaskFilterRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/task-assignment/getTaskDataDatail": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist"
                ],
                "summary": "Get Data Task Detail",
                "parameters": [
                    {
                        "description": "Task Filter",
                        "name": "taskFilter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TaskDetailRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/task-assignment/myTasklist": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist"
                ],
                "summary": "MyTasklist",
                "parameters": [
                    {
                        "description": "My Task Filter",
                        "name": "approvalRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TaskFilterRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/task-assignment/myTasklistDetail": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist"
                ],
                "summary": "MyTasklistDetail",
                "parameters": [
                    {
                        "description": "My Task Detail",
                        "name": "approvalRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TaskDetailRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/task-assignment/store": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "Tasklist"
                ],
                "summary": "Create Tasklist",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "name": "activity_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "approval",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "approval_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Quarter, Semester, Angka, Montly",
                        "name": "enable_range",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "end_date",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "kegiatan",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "maker_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "nama_tasklist",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "no_tasklist",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "period",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "name": "product_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "product_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "1",
                        "name": "range_date",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "example": true,
                        "name": "rap",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "risk_indicator",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "name": "risk_indicator_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "risk_issue",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "name": "risk_issue_id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "name": "sample",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "start_date",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "sumber_data",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "name": "task_type",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "task_type_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "validation",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "validation_name",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "File Uploader",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/task-assignment/update/{id}": {
            "put": {
                "tags": [
                    "Tasklist"
                ],
                "summary": "Update Tasklist",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tasklist ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "name": "activity_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "approval",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "approval_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Quarter, Semester, Angka, Montly",
                        "name": "enable_range",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "end_date",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "kegiatan",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "maker_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "nama_tasklist",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "no_tasklist",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "period",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "name": "product_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "product_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "1",
                        "name": "range_date",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "example": true,
                        "name": "rap",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "risk_indicator",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "name": "risk_indicator_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "risk_issue",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "name": "risk_issue_id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "name": "sample",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "start_date",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "sumber_data",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "name": "task_type",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "task_type_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "validation",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "example": "Test Create something",
                        "name": "validation_name",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "File Uploader",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/task-assignment/validation": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Validation Tasklist",
                "parameters": [
                    {
                        "description": "Tasklist Validation",
                        "name": "tasklist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TasklistsValidation"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/task-assignment/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist"
                ],
                "summary": "Get One Tasklist By Id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tasklist ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/anomaliHeader": {
            "post": {
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Get Anomali Header",
                "parameters": [
                    {
                        "description": "Tasklist Anomali Header",
                        "name": "tasklist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AnomaliHeader"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/anomaliValue": {
            "post": {
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Get Anomali Value",
                "parameters": [
                    {
                        "description": "Tasklist Anomali Value",
                        "name": "tasklist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AnomaliValue"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/approval": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Approval Tasklist",
                "parameters": [
                    {
                        "description": "Tasklist Approval",
                        "name": "tasklist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TasklistsAprrovalRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/checkAvailability": {
            "post": {
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Check Availability",
                "parameters": [
                    {
                        "description": "Tasklist Filter",
                        "name": "filter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TasklistsCheckRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/count": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Count Tasklist",
                "parameters": [
                    {
                        "description": "Tasklist Count",
                        "name": "tasklist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TasklistCountRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/delete": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Delete Tasklist",
                "parameters": [
                    {
                        "description": "Tasklist Filter",
                        "name": "filter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TasklistsUpdateDelete"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/downloadLampiranIndicatorTemplate": {
            "post": {
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Download Lampiran Indicator Template",
                "parameters": [
                    {
                        "description": "Lampiran Indicator",
                        "name": "tasklist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LampiranIndikatorCheck"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/filter": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Get Tasklist Filter",
                "parameters": [
                    {
                        "description": "Tasklist Filter",
                        "name": "filter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TasklistsFilterRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/filterByID": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Get Tasklist Filter By ID",
                "parameters": [
                    {
                        "description": "Tasklist Filter",
                        "name": "filter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TasklistsFilterRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/filterOfficer": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Get Tasklist Filter By Officer",
                "parameters": [
                    {
                        "description": "Tasklist Filter",
                        "name": "filter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TasklistsFilterOfficerRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/getAll": {
            "post": {
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Get All Tasklist",
                "parameters": [
                    {
                        "description": "Tasklist ID",
                        "name": "paginate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/riskmanagement_models_tasklists.Paginate"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/getAllOfficer": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Get All Officer",
                "parameters": [
                    {
                        "description": "Tasklist ID",
                        "name": "paginate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/riskmanagement_models_tasklists.Paginate"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/getDataAnomali": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Get Data Anomaly",
                "parameters": [
                    {
                        "description": "Tasklist ID",
                        "name": "TasklistID",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TasklistDataAnomaliRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/getDataVerifikasi": {
            "post": {
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Get Data Verifikasi",
                "parameters": [
                    {
                        "description": "Data Verifikasi",
                        "name": "tasklist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DataVerifikasiRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/getDone": {
            "post": {
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Get Done Tasklist",
                "parameters": [
                    {
                        "description": "Tasklist Done History",
                        "name": "tasklist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TasklistsDoneHistoryCheckRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/getFirstLampiran": {
            "post": {
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Get First Lampiran",
                "parameters": [
                    {
                        "description": "Tasklist Get First Lampiran",
                        "name": "tasklist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.GetFirstLampiranRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/getLampiranIndicator": {
            "post": {
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Get Lampiran Indicator",
                "parameters": [
                    {
                        "description": "Lampiran Indicator",
                        "name": "tasklist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LampiranIndikatorCheck"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/getOne": {
            "post": {
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Get One Tasklist By Id",
                "parameters": [
                    {
                        "description": "Tasklist ID",
                        "name": "tasklist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TasklistRequestOne"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/getTaskByID": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Get One Tasklist By Id",
                "parameters": [
                    {
                        "description": "Tasklist ID",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.GetTaskByID"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/insertTasklistRejected": {
            "post": {
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Insert Tasklist Rejected",
                "parameters": [
                    {
                        "description": "Tasklist Rejected",
                        "name": "tasklist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/riskmanagement_models_tasklists.TasklistsRejected"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/leadAutocompleteApr": {
            "post": {
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Lead Autocomplete Apr",
                "parameters": [
                    {
                        "description": "Lead Autocomplete",
                        "name": "tasklist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LeadAutocompleteRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/leadAutocompleteVal": {
            "post": {
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Lead Autocomplete Val",
                "parameters": [
                    {
                        "description": "Lead Autocomplete",
                        "name": "tasklist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LeadAutocompleteRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/store": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Store Tasklist",
                "parameters": [
                    {
                        "description": "Tasklist Filter",
                        "name": "filter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TasklistsStoreRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/storeDaily": {
            "post": {
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Insert StoreDaily",
                "parameters": [
                    {
                        "description": "Tasklist Daily Store",
                        "name": "tasklist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TasklistDailyStore"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/storeDone": {
            "post": {
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Store Done Tasklist",
                "parameters": [
                    {
                        "description": "Tasklist Done History",
                        "name": "tasklist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TasklistsDoneHistoryRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/update": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Update Tasklist",
                "parameters": [
                    {
                        "description": "Tasklist Filter",
                        "name": "filter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TasklistsUpdateRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/updateDaily": {
            "post": {
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Update Daily",
                "parameters": [
                    {
                        "description": "Tasklist Daily Store",
                        "name": "tasklist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ProgresUpdateRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/updateEndDate": {
            "post": {
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "Update End Date Tasklist",
                "parameters": [
                    {
                        "description": "Tasklist Filter",
                        "name": "filter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TasklistsUpdateEndDateRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/tasklists/userRegion": {
            "post": {
                "tags": [
                    "Tasklist (Old)"
                ],
                "summary": "User Region",
                "parameters": [
                    {
                        "description": "User Region",
                        "name": "tasklist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserRegionRequest"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "files.FilesRequest": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "extension": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.AnomaliHeader": {
            "type": "object",
            "properties": {
                "risk_indicator": {
                    "type": "string"
                },
                "risk_issue": {
                    "type": "string"
                },
                "tasklist_id": {
                    "type": "string"
                }
            }
        },
        "models.AnomaliValue": {
            "type": "object",
            "properties": {
                "risk_indicator": {
                    "type": "string",
                    "example": "Risk Indicator Example"
                },
                "risk_issue": {
                    "type": "string",
                    "example": "Risk Issue Example"
                },
                "tasklist_id": {
                    "type": "string",
                    "example": "1"
                }
            }
        },
        "models.CheckTableRequest": {
            "type": "object",
            "properties": {
                "risk_indicator_id": {
                    "type": "integer"
                },
                "risk_issue_id": {
                    "type": "integer"
                }
            }
        },
        "models.DataTematikRequest": {
            "type": "object",
            "properties": {
                "branch": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "risk_event": {
                    "type": "integer"
                },
                "risk_indicator": {
                    "type": "integer"
                }
            }
        },
        "models.DataVerifikasiRequest": {
            "type": "object",
            "properties": {
                "tasklist_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.DeleteTasklistDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "pernr": {
                    "type": "string",
                    "example": "P0000001"
                }
            }
        },
        "models.GetFirstLampiranRequest": {
            "type": "object",
            "properties": {
                "risk_indicator": {
                    "type": "string",
                    "example": "Risk Indicator Example"
                },
                "risk_issue": {
                    "description": "TasklistID    string ` + "`" + `json:\"tasklist_id\"` + "`" + `",
                    "type": "string",
                    "example": "Risk Issue Example"
                }
            }
        },
        "models.GetTaskByID": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.LampiranIndikatorCheck": {
            "type": "object",
            "properties": {
                "risk_indicator_id": {
                    "type": "string",
                    "example": "1"
                },
                "risk_issue_id": {
                    "type": "string",
                    "example": "1"
                }
            }
        },
        "models.LeadAutocompleteRequest": {
            "type": "object",
            "properties": {
                "keyword": {
                    "type": "string",
                    "example": "KCP PONDOK INDAH"
                },
                "region": {
                    "type": "string",
                    "example": "DKI JAKARTA"
                }
            }
        },
        "models.NoTaskRequest": {
            "type": "object",
            "properties": {
                "orgeh": {
                    "type": "string"
                },
                "pernr": {
                    "type": "string"
                }
            }
        },
        "models.ProgresUpdateRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "progres": {
                    "type": "integer",
                    "example": 50
                }
            }
        },
        "models.TaskApprovalRequest": {
            "type": "object",
            "properties": {
                "aktifitas": {
                    "type": "integer"
                },
                "branches": {
                    "type": "string"
                },
                "kanca": {
                    "type": "string"
                },
                "kanwil": {
                    "type": "string"
                },
                "kostl": {
                    "type": "string"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "pernr": {
                    "type": "string"
                },
                "product": {
                    "type": "integer"
                },
                "risk_event": {
                    "type": "integer"
                },
                "risk_indicator": {
                    "type": "integer"
                },
                "status_approval": {
                    "type": "string"
                },
                "status_document": {
                    "type": "string"
                },
                "status_task": {
                    "type": "string"
                },
                "task_type": {
                    "type": "integer"
                },
                "uker": {
                    "type": "string"
                },
                "validator": {
                    "type": "string"
                }
            }
        },
        "models.TaskDetailRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "pernr": {
                    "type": "string"
                }
            }
        },
        "models.TaskFilterRequest": {
            "type": "object",
            "properties": {
                "aktifitas": {
                    "type": "integer",
                    "example": 1
                },
                "branches": {
                    "type": "string",
                    "example": "Test"
                },
                "kanca": {
                    "type": "string",
                    "example": "Test"
                },
                "kanwil": {
                    "type": "string",
                    "example": "Test"
                },
                "kostl": {
                    "type": "string",
                    "example": "Test"
                },
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "pernr": {
                    "type": "string",
                    "example": "Test"
                },
                "product": {
                    "type": "integer",
                    "example": 1
                },
                "risk_event": {
                    "type": "integer",
                    "example": 1
                },
                "risk_indicator": {
                    "type": "integer",
                    "example": 1
                },
                "status_approval": {
                    "type": "string",
                    "example": "Test"
                },
                "status_document": {
                    "type": "string",
                    "example": "Test"
                },
                "status_task": {
                    "type": "string",
                    "example": "Test"
                },
                "task_type": {
                    "type": "integer",
                    "example": 1
                },
                "tgl_akhir": {
                    "type": "string",
                    "example": "2025-02-10"
                },
                "tgl_awal": {
                    "type": "string",
                    "example": "2025-02-01"
                },
                "uker": {
                    "type": "string",
                    "example": "Test"
                }
            }
        },
        "models.TasklistCountRequest": {
            "type": "object",
            "properties": {
                "branch": {
                    "type": "integer",
                    "example": 123
                },
                "pernr": {
                    "type": "string",
                    "example": "456"
                }
            }
        },
        "models.TasklistDailyStore": {
            "type": "object",
            "properties": {
                "activity_id": {
                    "description": "TasklistID      int64   ` + "`" + `json:\"tasklist_id\"` + "`" + `",
                    "type": "integer",
                    "example": 1
                },
                "approval": {
                    "type": "string",
                    "example": "Manual"
                },
                "approval_name": {
                    "type": "string",
                    "example": "Manual"
                },
                "approval_status": {
                    "type": "string",
                    "example": "Waiting"
                },
                "branch": {
                    "type": "string",
                    "example": "KC JAKARTA"
                },
                "brdesc": {
                    "type": "string",
                    "example": "KC JAKARTA"
                },
                "createdAt": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string",
                    "example": "2022-01-31"
                },
                "mainbr": {
                    "type": "string",
                    "example": "KANWIL JAWA"
                },
                "maker_id": {
                    "type": "string",
                    "example": "123456"
                },
                "mbdesc": {
                    "type": "string",
                    "example": "KANWIL JAWA"
                },
                "pernr": {
                    "type": "string",
                    "example": "123456"
                },
                "product_id": {
                    "type": "integer",
                    "example": 1
                },
                "product_name": {
                    "type": "string",
                    "example": "Kredit"
                },
                "progres": {
                    "type": "integer",
                    "example": 1
                },
                "rap": {
                    "type": "integer",
                    "example": 1
                },
                "region": {
                    "type": "string",
                    "example": "Jawa"
                },
                "rgdesc": {
                    "type": "string",
                    "example": "Jawa"
                },
                "risk_indicator": {
                    "type": "string",
                    "example": "Kredit Macet \u003e 3 Bulan"
                },
                "risk_indicator_id": {
                    "type": "integer",
                    "example": 1
                },
                "risk_issue": {
                    "type": "string",
                    "example": "Kredit Macet"
                },
                "risk_issue_id": {
                    "type": "integer",
                    "example": 1
                },
                "sample": {
                    "type": "integer",
                    "example": 1
                },
                "start_date": {
                    "type": "string",
                    "example": "2022-01-01"
                },
                "status": {
                    "type": "string",
                    "example": "Open"
                },
                "sumber_data": {
                    "type": "string",
                    "example": "Kanal"
                },
                "task_type": {
                    "type": "integer",
                    "example": 1
                },
                "task_type_name": {
                    "type": "string",
                    "example": "Daily"
                },
                "updatedAt": {
                    "type": "string"
                },
                "validation": {
                    "type": "string",
                    "example": "Manual"
                },
                "validation_name": {
                    "type": "string",
                    "example": "Manual"
                }
            }
        },
        "models.TasklistDataAnomaliRequest": {
            "type": "object",
            "properties": {
                "tasklist_id": {
                    "type": "string",
                    "example": "1"
                }
            }
        },
        "models.TasklistRequestOne": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.TasklistsAprrovalRequest": {
            "type": "object",
            "properties": {
                "approval": {
                    "type": "string",
                    "example": "approve"
                },
                "branch": {
                    "type": "string",
                    "example": "branch"
                },
                "id": {
                    "type": "integer",
                    "example": 123
                },
                "notes": {
                    "type": "string",
                    "example": "notes"
                },
                "receiver": {
                    "type": "string",
                    "example": "receiver"
                },
                "uker": {
                    "type": "string",
                    "example": "uker"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-10-01T00:00:00Z"
                }
            }
        },
        "models.TasklistsCheckRequest": {
            "type": "object",
            "properties": {
                "branch": {
                    "type": "string",
                    "example": "001"
                },
                "brdesc": {
                    "type": "string",
                    "example": "KCP BSD"
                },
                "brname": {
                    "type": "string",
                    "example": "KCP BSD"
                },
                "mainbr": {
                    "type": "string",
                    "example": "001"
                },
                "mbdesc": {
                    "type": "string",
                    "example": "KCP BSD"
                },
                "mbname": {
                    "type": "string",
                    "example": "KCP BSD"
                },
                "region": {
                    "type": "string",
                    "example": "Banten"
                },
                "rgdesc": {
                    "type": "string",
                    "example": "Banten"
                },
                "rgname": {
                    "type": "string",
                    "example": "Banten"
                },
                "risk_issue_id": {
                    "type": "integer",
                    "example": 1
                },
                "task_type": {
                    "type": "string",
                    "example": "1"
                },
                "unit_kerja": {
                    "type": "string",
                    "example": "KCP BSD"
                }
            }
        },
        "models.TasklistsDoneHistoryCheckRequest": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string",
                    "example": "2023-10-01"
                },
                "pernr": {
                    "type": "string",
                    "example": "456"
                },
                "tasklist_id": {
                    "type": "integer",
                    "example": 123
                }
            }
        },
        "models.TasklistsDoneHistoryRequest": {
            "type": "object",
            "properties": {
                "pernr": {
                    "type": "string",
                    "example": "456"
                },
                "tasklist_id": {
                    "type": "integer",
                    "example": 123
                }
            }
        },
        "models.TasklistsFilterOfficerRequest": {
            "type": "object",
            "properties": {
                "activity_id": {
                    "type": "integer",
                    "example": 1
                },
                "branch": {
                    "type": "string",
                    "example": "JAKARTA"
                },
                "brdesc": {
                    "type": "string",
                    "example": "JAKARTA"
                },
                "end_date": {
                    "type": "string",
                    "example": "2021-01-31"
                },
                "hilfm": {
                    "type": "string",
                    "example": "TEST"
                },
                "jenis_task": {
                    "type": "string",
                    "example": "TEST"
                },
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "mainbr": {
                    "type": "string",
                    "example": "JAKARTA"
                },
                "maker_id": {
                    "type": "string",
                    "example": "100001"
                },
                "mbdesc": {
                    "type": "string",
                    "example": "JAKARTA"
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "order": {
                    "type": "string",
                    "example": "DESC"
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "pernr": {
                    "type": "string",
                    "example": "100001"
                },
                "product_id": {
                    "type": "integer",
                    "example": 1
                },
                "region": {
                    "type": "string",
                    "example": "JAKARTA"
                },
                "rgdesc": {
                    "type": "string",
                    "example": "JAKARTA"
                },
                "risk_indicator": {
                    "type": "string",
                    "example": "TEST"
                },
                "risk_indicator_id": {
                    "type": "integer",
                    "example": 1
                },
                "risk_issue_id": {
                    "type": "integer",
                    "example": 1
                },
                "sort": {
                    "type": "string",
                    "example": "id"
                },
                "start_date": {
                    "type": "string",
                    "example": "2021-01-01"
                },
                "status": {
                    "type": "string",
                    "example": "PENDING"
                },
                "status_approval": {
                    "type": "string",
                    "example": "APPROVED"
                },
                "stell_tx": {
                    "type": "string",
                    "example": "TEST"
                },
                "tipe_uker": {
                    "type": "string",
                    "example": "TEST"
                }
            }
        },
        "models.TasklistsFilterRequest": {
            "type": "object",
            "properties": {
                "activity_id": {
                    "type": "integer",
                    "example": 1
                },
                "branch": {
                    "type": "string",
                    "example": "JAKARTA"
                },
                "brdesc": {
                    "type": "string",
                    "example": "JAKARTA"
                },
                "end_date": {
                    "type": "string",
                    "example": "2021-01-31"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "jenis_task": {
                    "type": "string",
                    "example": "TEST"
                },
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "mainbr": {
                    "type": "string",
                    "example": "JAKARTA"
                },
                "mbdesc": {
                    "type": "string",
                    "example": "JAKARTA"
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "order": {
                    "type": "string",
                    "example": "DESC"
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "pernr": {
                    "type": "string",
                    "example": "100001"
                },
                "product_id": {
                    "type": "integer",
                    "example": 1
                },
                "region": {
                    "type": "string",
                    "example": "JAKARTA"
                },
                "rgdesc": {
                    "type": "string",
                    "example": "JAKARTA"
                },
                "risk_indicator": {
                    "type": "string",
                    "example": "TEST"
                },
                "risk_indikator_id": {
                    "type": "integer",
                    "example": 1
                },
                "risk_issue_id": {
                    "type": "integer",
                    "example": 1
                },
                "sort": {
                    "type": "string",
                    "example": "id"
                },
                "start_date": {
                    "type": "string",
                    "example": "2021-01-01"
                },
                "status": {
                    "type": "string",
                    "example": "PENDING"
                },
                "status_approval": {
                    "type": "string",
                    "example": "APPROVED"
                },
                "tipe_uker": {
                    "type": "string",
                    "example": "TEST"
                }
            }
        },
        "models.TasklistsStoreRequest": {
            "type": "object",
            "properties": {
                "activity_id": {
                    "type": "integer"
                },
                "approval": {
                    "type": "string"
                },
                "approval_name": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "files": {
                    "description": "DataAnomaliKRID\t[]TasklistsAnomaliDataKRIDRequest\t` + "`" + `json:\"data_anomali_krid\"` + "`" + `",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/files.FilesRequest"
                    }
                },
                "header_lampiran": {
                    "description": "IsiLampiran\t[]Lampiran\t` + "`" + `json:\"isi_lampiran\"` + "`" + `",
                    "type": "string"
                },
                "isi_lampiran": {
                    "type": "array",
                    "items": {}
                },
                "jenis_task": {
                    "type": "integer"
                },
                "jumlah_kolom": {
                    "type": "integer"
                },
                "kegiatan": {
                    "type": "string"
                },
                "maker_id": {
                    "type": "string"
                },
                "period": {
                    "type": "string"
                },
                "product_id": {
                    "type": "integer"
                },
                "product_name": {
                    "type": "string"
                },
                "rap": {
                    "type": "string"
                },
                "risk_indicator": {
                    "description": "RiskIndicator \t\t\t[]TasklistsRiskIndicator\t\t\t` + "`" + `json:\"risk_indicator\"` + "`" + `",
                    "type": "string"
                },
                "risk_indicator_id": {
                    "type": "integer"
                },
                "risk_issue": {
                    "type": "string"
                },
                "risk_issue_id": {
                    "type": "integer"
                },
                "sample": {
                    "type": "integer"
                },
                "start_date": {
                    "type": "string"
                },
                "sumber_data": {
                    "type": "string"
                },
                "task_type_name": {
                    "type": "string"
                },
                "uker": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TasklistsUker"
                    }
                },
                "validation": {
                    "type": "string"
                },
                "validation_name": {
                    "type": "string"
                }
            }
        },
        "models.TasklistsUker": {
            "type": "object",
            "properties": {
                "branch": {
                    "type": "string"
                },
                "brdesc": {
                    "type": "string"
                },
                "brname": {
                    "type": "string"
                },
                "mainbr": {
                    "type": "string"
                },
                "mbdesc": {
                    "type": "string"
                },
                "mbname": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "rgdesc": {
                    "type": "string"
                },
                "rgname": {
                    "type": "string"
                },
                "tasklistID": {
                    "type": "integer"
                },
                "unit_kerja": {
                    "type": "string"
                }
            }
        },
        "models.TasklistsUpdateDelete": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 123
                },
                "status": {
                    "type": "string",
                    "example": "active"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-10-01T00:00:00Z"
                }
            }
        },
        "models.TasklistsUpdateEndDateRequest": {
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string",
                    "example": "2023-12-31"
                },
                "id": {
                    "type": "integer",
                    "example": 123
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-10-01T00:00:00Z"
                }
            }
        },
        "models.TasklistsUpdateRequest": {
            "type": "object",
            "properties": {
                "activity_id": {
                    "type": "integer",
                    "example": 456
                },
                "approval": {
                    "type": "string",
                    "example": "Approved"
                },
                "approval_name": {
                    "type": "string",
                    "example": "Approval Name"
                },
                "created_at": {
                    "type": "string",
                    "example": "2023-10-01T00:00:00Z"
                },
                "end_date": {
                    "type": "string",
                    "example": "2023-12-31"
                },
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/files.FilesRequest"
                    }
                },
                "header_lampiran": {
                    "type": "string",
                    "example": "Header"
                },
                "id": {
                    "type": "integer",
                    "example": 123
                },
                "isi_lampiran": {
                    "type": "array",
                    "items": {}
                },
                "jenis_task": {
                    "type": "integer",
                    "example": 1
                },
                "jumlah_kolom": {
                    "type": "integer",
                    "example": 5
                },
                "kegiatan": {
                    "type": "string",
                    "example": "Activity"
                },
                "maker_id": {
                    "type": "string",
                    "example": "Maker123"
                },
                "period": {
                    "type": "string",
                    "example": "2023-10"
                },
                "product_id": {
                    "type": "integer",
                    "example": 789
                },
                "product_name": {
                    "type": "string",
                    "example": "Product A"
                },
                "rap": {
                    "type": "string",
                    "example": "RAP Data"
                },
                "risk_indicator": {
                    "type": "string",
                    "example": "Low"
                },
                "risk_indicator_id": {
                    "type": "integer",
                    "example": 223
                },
                "risk_issue": {
                    "type": "string",
                    "example": "Issue"
                },
                "risk_issue_id": {
                    "type": "integer",
                    "example": 112
                },
                "sample": {
                    "type": "string",
                    "example": "Sample Data"
                },
                "start_date": {
                    "type": "string",
                    "example": "2023-10-01"
                },
                "sumber_data": {
                    "type": "string",
                    "example": "External"
                },
                "task_type_name": {
                    "type": "string",
                    "example": "Type A"
                },
                "uker": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TasklistsUker"
                    }
                },
                "validation": {
                    "type": "string",
                    "example": "Validated"
                },
                "validation_name": {
                    "type": "string",
                    "example": "Validation Name"
                }
            }
        },
        "models.TasklistsValidation": {
            "type": "object",
            "properties": {
                "branch": {
                    "type": "string",
                    "example": "branch"
                },
                "id": {
                    "type": "integer"
                },
                "notes": {
                    "type": "string",
                    "example": "notes"
                },
                "receiver": {
                    "type": "string",
                    "example": "receiver"
                },
                "uker": {
                    "type": "string",
                    "example": "uker"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-10-01T00:00:00Z"
                },
                "validation": {
                    "type": "string",
                    "example": "rejected"
                }
            }
        },
        "models.UserRegionRequest": {
            "type": "object",
            "properties": {
                "branch": {
                    "type": "integer",
                    "example": 123
                }
            }
        },
        "riskmanagement_models_taskassignment.ApprovalRequest": {
            "type": "object",
            "properties": {
                "approval": {
                    "description": "This is of type ApprovalEnum",
                    "type": "string",
                    "example": "approve"
                },
                "branch": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "0"
                    ]
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "notes": {
                    "type": "string",
                    "example": "Test Create something"
                },
                "pernr": {
                    "type": "string",
                    "example": "P0000001"
                }
            }
        },
        "riskmanagement_models_tasklists.Paginate": {
            "type": "object",
            "properties": {
                "branch": {
                    "type": "string",
                    "example": "KCP PONDOK INDAH"
                },
                "hilfm": {
                    "type": "string",
                    "example": "KCP001"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "mainbr": {
                    "type": "string",
                    "example": "KCP PONDOK INDAH"
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "order": {
                    "type": "string",
                    "example": "asc"
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "period": {
                    "type": "string",
                    "example": "2022"
                },
                "pernr": {
                    "type": "string",
                    "example": "123456"
                },
                "region": {
                    "type": "string",
                    "example": "DKI JAKARTA"
                },
                "sort": {
                    "type": "string",
                    "example": "id"
                },
                "stell_tx": {
                    "type": "string",
                    "example": "KCP PONDOK INDAH"
                },
                "tipe_uker": {
                    "type": "string",
                    "example": "KCP"
                },
                "unit_kerja": {
                    "type": "string",
                    "example": "KCP PONDOK INDAH"
                }
            }
        },
        "riskmanagement_models_tasklists.TasklistsRejected": {
            "type": "object",
            "properties": {
                "notes": {
                    "type": "string",
                    "example": "notes"
                },
                "status": {
                    "type": "string",
                    "example": "rejected"
                },
                "tasklist_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
